task: IqaTask_V0
template: ./templates/iqa/iqa_react.json

world:

question_type: 0

agents:
  - type: ChatAgent
    from_user: True
    debug: True
    llm:
      llm_type: ChatOpenAI
    inventory_capacity: 1
    focal_length: 10
    max_manipulate_distance: 2
    max_view_distance: 2
    step_size: 0.25
    # view_degree: 60.0
