task: BabyAITask:BabyAIEnv
template: ./langsuite/envs/babyai/templates/babyai_react_expert.json

env:
  type: BabyAIEnv

world:
  type: BabyAIWorld
  id: BabyAI-1RoomS8-v0
  seed: 4

agents:
  - type: BabyAIExpertAgent
    llm:
      llm_type: "ChatOpenAI"
