task: RearrangementTask:Rearrange2DEnv
template: ./langsuite/envs/rearrange/templates/rearrange_react_expert.json

env:
  type: Rearrange2DEnv

world:
  type: RearrangeWorld
  id: rearrange_world
  grid_size: 0.25

agents:
  - type: RearrangeExpertAgent
    position: 'random'
    inventory_capacity: 1
    focal_length: 10
    max_manipulate_distance: 2
    max_view_distance: 2
    step_size: 0.25
    llm:
      llm_type: "ChatOpenAI"
